#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Every stage assumes the repo root: gh writes to the repo of the working
# directory, and the terraform paths below are relative.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Captured values live here, not in .env: .env is the app's own config, copied
# from .env.example. .env.deploy is gitignored by the .env.* rule.
ENV_FILE=".env.deploy"

GITHUB_REPOSITORY_SLUG="Teekola/electricity-app"

# ask_valid KEY "Prompt" REGEX "hint" re-asks until the answer matches, so a
# blank or malformed value never reaches gcloud or terraform.
ask_valid() {
  local key="$1" prompt="$2" pattern="$3" hint="$4"
  while true; do
    ask "$key" "$prompt"
    [[ "${!key}" =~ $pattern ]] && return 0
    warn "$hint"
  done
}

# run_step "what" cmd... offers a retry instead of killing the wizard. Almost
# everything fallible here is a browser flow or an API still propagating.
run_step() {
  local what="$1"; shift
  while true; do
    if "$@"; then return 0; fi
    say ""
    warn "$what did not succeed."
    confirm "Try it again?" && continue
    if confirm "Skip it and carry on?"; then
      SKIPPED+=("$what")
      return 1
    fi
    say ""
    note "Stopping here. Re-run this wizard when ready; it remembers what it"
    note "already captured in $ENV_FILE."
    exit 1
  done
}

IS_WSL=0
grep -qi microsoft /proc/version 2>/dev/null && IS_WSL=1

banner "First deploy: Google Cloud + Vercel"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Tooling"
say "Checking the three CLIs this needs. They live under your home directory,"
say "so this puts them on PATH for the rest of the wizard."

export PATH="$HOME/.local/bin:$HOME/google-cloud-sdk/bin:$PATH"

missing=0
for tool in gcloud terraform gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %-10s %s\n' "$GREEN" "$RESET" "$tool" "$(command -v "$tool")"
  else
    warn "$tool is not on PATH"
    missing=1
  fi
done

if (( missing )); then
  warn "Install the missing tool(s), then re-run this wizard."
  exit 1
fi

say ""
if confirm "Add these to PATH permanently in ~/.bashrc?"; then
  {
    printf '\n# Added by scripts/first-deploy.sh\n'
    printf 'export PATH="$HOME/.local/bin:$HOME/google-cloud-sdk/bin:$PATH"\n'
  } >> "$HOME/.bashrc"
  printf '  %s✓%s appended to ~/.bashrc\n' "$GREEN" "$RESET"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in to Google Cloud"

# On WSL the default flow launches the Windows browser and waits for a
# redirect to localhost inside WSL, which is what fails with "missing_code".
# --no-launch-browser swaps it for a copy-paste code and no redirect at all.
LOGIN_FLAGS=()
if (( IS_WSL )); then
  LOGIN_FLAGS=(--no-launch-browser)
  note "WSL detected, so this uses the copy-paste code flow: the browser"
  note "redirect back to localhost does not survive the Windows/WSL boundary."
  say ""
fi

say "Two logins are needed. For each one:"
step "Copy the long https://accounts.google.com/... URL that gcloud prints."
step "Paste it into your browser and approve the access."
step "Copy the authorization code shown, and paste it back here."
say ""
note "First: gcloud auth login, for this wizard's own gcloud commands."
pause "Press Enter to start"

run_step "gcloud auth login" gcloud auth login "${LOGIN_FLAGS[@]}"

say ""
note "Second: application-default login, which is the credential Terraform reads."
note "This is a separate credential; signing in once does not cover both."
pause "Press Enter to start"

run_step "gcloud auth application-default login" \
  gcloud auth application-default login "${LOGIN_FLAGS[@]}"

GCP_ACCOUNT="$(gcloud config get-value account 2>/dev/null || true)"
if [[ -z "$GCP_ACCOUNT" || "$GCP_ACCOUNT" == "(unset)" ]]; then
  warn "No active account, so nothing below would work."
  note "Re-run this wizard once gcloud auth login succeeds."
  exit 1
fi
printf '  %s✓%s signed in as %s\n' "$GREEN" "$RESET" "$GCP_ACCOUNT"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Project and billing"
say "Cloud SQL will not provision without billing, so this stage ends by"
say "checking that billing is actually enabled."
say ""
say "Projects you can already see:"
gcloud projects list --format="table(projectId, name)" 2>/dev/null || note "  (none)"
say ""

if confirm "Create a NEW project for this app?"; then
  note "6-30 characters, starting with a lowercase letter, and globally unique"
  note "across all of Google Cloud, so add something random."
  ask_valid GCP_PROJECT_ID "New project ID:" \
    '^[a-z][a-z0-9-]{4,28}[a-z0-9]$' \
    "Must be 6-30 chars: lowercase letter first, then letters, digits or hyphens."
  run_step "gcloud projects create $GCP_PROJECT_ID" \
    gcloud projects create "$GCP_PROJECT_ID" --name="Electricity app"
else
  ask_valid GCP_PROJECT_ID "Existing project ID to deploy into:" \
    '^[a-z][a-z0-9-]{4,28}[a-z0-9]$' \
    "Must be 6-30 chars: lowercase letter first, then letters, digits or hyphens."
fi

if ! gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  warn "Cannot see project $GCP_PROJECT_ID with this account."
  note "Check the ID, then re-run this wizard."
  exit 1
fi

gcloud config set project "$GCP_PROJECT_ID" >/dev/null
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

ask GCP_REGION "Region [Enter for europe-north1, Hamina, Finland]:"
GCP_REGION="${GCP_REGION:-europe-north1}"
write_env GCP_REGION "$GCP_REGION"

say ""
say "Billing accounts open to you:"
gcloud billing accounts list --format="table(name, displayName, open)" 2>/dev/null \
  || warn "could not list billing accounts"
say ""
note "Paste just the ID, e.g. 01ABCD-2345EF-6789GH. Blank opens the console instead."
ask GCP_BILLING_ACCOUNT "Billing account ID:"

if [[ "$GCP_BILLING_ACCOUNT" =~ ^[A-F0-9]{6}-[A-F0-9]{6}-[A-F0-9]{6}$ ]]; then
  run_step "linking billing" gcloud billing projects link "$GCP_PROJECT_ID" \
    --billing-account="$GCP_BILLING_ACCOUNT"
  write_env GCP_BILLING_ACCOUNT "$GCP_BILLING_ACCOUNT"
else
  [[ -n "$GCP_BILLING_ACCOUNT" ]] && warn "That is not an XXXXXX-XXXXXX-XXXXXX ID; using the console instead."
  open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
  step "Link a billing account to this project, then come back."
  pause
fi

say ""
while true; do
  BILLING_ON="$(gcloud billing projects describe "$GCP_PROJECT_ID" \
    --format='value(billingEnabled)' 2>/dev/null || true)"
  if [[ "$BILLING_ON" == "True" ]]; then
    printf '  %s✓%s billing is enabled\n' "$GREEN" "$RESET"
    break
  fi
  warn "Billing is not enabled on $GCP_PROJECT_ID yet."
  note "Cloud SQL creation in the deploy will fail without it."
  confirm "Check again?" || { SKIPPED+=("enable billing on $GCP_PROJECT_ID"); break; }
done
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Bootstrap Google Cloud"
say "This applies infra/bootstrap: enables the APIs, and creates the Terraform"
say "state bucket, the image registry, and the identity GitHub Actions uses."
say ""
warn "This creates real resources in $GCP_PROJECT_ID."
note "The bucket and registry cost cents. Cloud SQL comes later in the deploy"
note "itself, and is the part that bills: roughly \$10-15/month at these defaults."
say ""

if ! confirm "Apply infra/bootstrap now?"; then
  SKIPPED+=("infra/bootstrap not applied; re-run this wizard")
  warn "skipped"
else
  cat > infra/bootstrap/terraform.tfvars <<TFVARS
project_id        = "$GCP_PROJECT_ID"
region            = "$GCP_REGION"
github_repository = "$GITHUB_REPOSITORY_SLUG"
TFVARS
  printf '  %s✓ wrote%s infra/bootstrap/terraform.tfvars\n' "$GREEN" "$RESET"

  run_step "terraform init" terraform -chdir=infra/bootstrap init -input=false

  # Enabling an API and using it in the same apply can race, so a first-run
  # failure here is usually cured by applying again a minute later.
  note "If this fails on a newly enabled API, retrying usually fixes it."
  if run_step "terraform apply (bootstrap)" \
       terraform -chdir=infra/bootstrap apply -input=false -auto-approve; then
    TF_STATE_BUCKET=$(terraform -chdir=infra/bootstrap output -raw state_bucket)
    ARTIFACT_REGISTRY_REPO=$(terraform -chdir=infra/bootstrap output -raw artifact_registry_repository)
    GCP_WORKLOAD_IDENTITY_PROVIDER=$(terraform -chdir=infra/bootstrap output -raw workload_identity_provider)
    GCP_SERVICE_ACCOUNT=$(terraform -chdir=infra/bootstrap output -raw deployer_service_account)

    write_env TF_STATE_BUCKET "$TF_STATE_BUCKET"
    write_env ARTIFACT_REGISTRY_REPO "$ARTIFACT_REGISTRY_REPO"
    write_env GCP_WORKLOAD_IDENTITY_PROVIDER "$GCP_WORKLOAD_IDENTITY_PROVIDER"
    write_env GCP_SERVICE_ACCOUNT "$GCP_SERVICE_ACCOUNT"
  fi
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel token"
say "Terraform creates the Vercel project itself, so nothing needs to exist"
say "there first. It only needs a token."
open_url "https://vercel.com/account/settings/tokens"
step "Click 'Create Token'."
step "Name it something like 'electricity-app terraform'."
step "Scope it to the account or team you want the project in."
step "Set an expiry you are happy to rotate on, then create and copy it."
while true; do
  ask_secret VERCEL_API_TOKEN "Paste the token:"
  [[ -n "$VERCEL_API_TOKEN" ]] && break
  warn "The deploy cannot manage Vercel without it."
done
write_env VERCEL_API_TOKEN "$VERCEL_API_TOKEN"

say ""
say "If the project belongs to a TEAM rather than your personal account,"
say "Terraform needs the team slug. Leave blank for a personal account."
ask VERCEL_TEAM "Vercel team slug:"
[[ -n "$VERCEL_TEAM" ]] && write_env VERCEL_TEAM "$VERCEL_TEAM"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Sign in to GitHub"
say "Needed to write the repository variables and the secret, and to set"
say "branch protection on main."

if gh auth status >/dev/null 2>&1; then
  printf '  %s✓%s already authenticated\n' "$GREEN" "$RESET"
else
  step "Choose GitHub.com, then HTTPS."
  (( IS_WSL )) && step "Prefer 'Paste an authentication token' if the browser flow stalls."
  pause "Press Enter to start gh auth login"
  run_step "gh auth login" gh auth login
fi

if gh repo view "$GITHUB_REPOSITORY_SLUG" --json nameWithOwner -q .nameWithOwner 2>/dev/null; then
  printf '  %s✓%s can reach %s\n' "$GREEN" "$RESET" "$GITHUB_REPOSITORY_SLUG"
else
  warn "cannot reach $GITHUB_REPOSITORY_SLUG with this account"
  SKIPPED+=("GitHub access to $GITHUB_REPOSITORY_SLUG")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Repository variables and secret"
say "Writing the values the two workflows read. Anything blank is reported at"
say "the end rather than written, since a blank variable fails the deploy."

set_var_checked() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("GitHub variable $name (bootstrap did not run)")
    warn "$name is empty, so not writing it"
    return
  fi
  set_var "$name" "$value"
}

set_var_checked GCP_PROJECT_ID                 "$GCP_PROJECT_ID"
set_var_checked GCP_REGION                     "$GCP_REGION"
set_var_checked TF_STATE_BUCKET                "${TF_STATE_BUCKET:-}"
set_var_checked ARTIFACT_REGISTRY_REPO         "${ARTIFACT_REGISTRY_REPO:-}"
set_var_checked GCP_WORKLOAD_IDENTITY_PROVIDER "${GCP_WORKLOAD_IDENTITY_PROVIDER:-}"
set_var_checked GCP_SERVICE_ACCOUNT            "${GCP_SERVICE_ACCOUNT:-}"

if [[ -n "${VERCEL_TEAM:-}" ]]; then
  set_var VERCEL_TEAM "$VERCEL_TEAM"
else
  note "VERCEL_TEAM left unset, which the Terraform reads as a personal account."
fi

set_secret VERCEL_API_TOKEN "$VERCEL_API_TOKEN"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Protect main"
say "deploy.yml does not re-run CI: it trusts the pull request's run. That is"
say "only safe if nothing can reach main without having passed CI, so this"
say "requires both checks, requires branches to be up to date, and blocks"
say "direct pushes."
say ""
warn "After this you cannot push straight to main, including as the owner."
note "Every change goes through a pull request. DEPLOYING.md explains how to"
note "undo this if you would rather keep pushing directly."
say ""

if confirm "Protect main now?"; then
  if gh api -X PUT "repos/$GITHUB_REPOSITORY_SLUG/branches/main/protection" --input - <<'JSON'
{
  "required_status_checks": {
    "strict": true,
    "contexts": ["Lint, typecheck, test, build", "End-to-end"]
  },
  "enforce_admins": true,
  "required_pull_request_reviews": null,
  "restrictions": null,
  "allow_force_pushes": false,
  "allow_deletions": false
}
JSON
  then
    printf '  %s✓%s main is protected\n' "$GREEN" "$RESET"
  else
    warn "could not set branch protection"
    SKIPPED+=("branch protection on main (see DEPLOYING.md step 4)")
  fi
else
  SKIPPED+=("branch protection on main — deploy.yml has no CI gate without it")
  warn "skipped, so an untested commit on main would deploy"
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "First deploy"
say "Configuration is done. The deploy triggers on a push to main."
say ""
say "Commit and push yourself:"
say ""
note '  git switch -c deploy-to-cloud'
note '  git add .'
note '  git commit'
note '  git push -u origin deploy-to-cloud'
note '  gh pr create --fill && gh pr merge --squash'
say ""
say "Suggested commit message:"
note '  feat: deploy to Cloud Run, Cloud SQL and Vercel via Terraform'
say ""
warn "The first run takes ~15 minutes; most of it is Cloud SQL provisioning."
pause "Press Enter once you have pushed and merged"

if confirm "Follow the deploy run now?"; then
  gh run watch --exit-status \
    || warn "not green; inspect it with: gh run view --log-failed"
fi

finish
note "$ENV_FILE holds the captured values, including the Vercel token, and is"
note "gitignored. Delete it once the GitHub variables are set if you would"
note "rather not keep a token on disk."
